# Generated by Django 4.2.8 on 2023-12-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='receiver_user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='sender_user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
