version: '3.8'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: cats_blog
      POSTGRES_PASSWORD: cats_blog

  web:
    build: .
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: cats_blog
      DB_PASSWORD: cats_blog
      DB_USER: cats_blog
      REDIS_HOST: redis
      REDIS_PORT: 6379

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - web

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=cats_blog
      - REDIS_PORT=6379
      - REDIS_DATABASES=16

volumes:
  static_volume:
  media_volume:
  db_data: